---
title: "Final Project"
date: "2023-12-06"
format: 
  html:
    embed-resources: true
    code-tools: true
    code-summary: "Code"
---
 
 
## Introduction

For this project, you will be exploring data on a topic of your choice. You should choose a dataset that interests you and will enable you to demonstrate the exploration, visualization, and analysis skills you have learned this semester.

You will use your selected dataset to conduct an exploratory data analysis as well as a statistical analysis (hypothesis test or regression analysis) to explore a set of research questions of your own choice.

Your projects will be evaluated on your use of code to perform your analysis as well as the quality of your visualizations and exposition. This includes, but is not limited to, the quality of your writing, the informativeness of your visualizations, and the depth of research questions. The target audience of your report is a peer who is uninformed about the details of the data, but is interested in learning more about your analysis. Again, **there are no right answers for this project!** Successful projects will involve more than a cursory analysis of one or two variables in the dataset and will tell a compelling story about the dataset.

## Part One: Project Proposal (10 points), due 10/13

## Part Two: Final Report (70 points), due 12/8

## Part Three: Lightning Talks (15 points), slides due 12/3

## Part Four: Reflection and Self-evaluation (5 points), due 12/12


### Details

1.  Choose a data set or multiple datasets with the following characteristics:
    a.  At least three continuous variables
    b.  At least two categorical variables
2.  Identify three research questions of interest that you want to study using this dataset. Each of your research questions should involve at least two of the variables in your dataset.
3.  For each of your three research questions, generate at least one data visualization or descriptive statistic. Discuss and interpret your findings.
4.  For at least one of your research questions, perform a statistical analysis (ex. hypothesis test, confidence interval, linear regression). Discuss and interpret your findings.
5.  Final submissions must include .Rmd and .html files.
6.  If you are an undergraduate interested in participating in a competition and potentially presenting at the Electronic Undergraduate Statistics Conference, you may consider using this project to submit to the [Undergraduate Class Project Competition](https://www.causeweb.org/usproc/usclap).

## Part One: Project Proposal (10 points), due 10/13

You will submit a 1-2 page project proposal with the following information:

-   A brief description of your dataset (where it is from, how it can be obtained, why you chose it).

-   A **data dictionary** in the following format (if there are more than 10 variables, you can choose the 10 variables that interest you most):

    | Variable name | Variable type | Description   |
    |---------------|---------------|---------------|
    | ex. `dob`     | Date          | date of birth |
    | ex. `city`    | character     | city of birth |
    | . . .         | . . .         | . . .         |

-   An overview of the main research questions you hope to explore through your project. Each of your research questions should involve at least two of the variables in your dataset.

-   A list of three to five outside references you plan to consult for background reading on your research questions.

-   Any questions you have for me.

## Part Two: Final Report (70 points), due 12/8

5-7 pages, including figures. You do not have to write this in the form of an essay, but you should present your findings in a clear and organized way. In particular, you should be sure to cover the following areas:

-   **Introduction and background**: 
    - Introduce your dataset and research questions of interest. Each of your research questions should involve at least two of the variables in your dataset.
    - Discuss any previous research/findings or relevant context on your question of interest. 
    - Provide a univariate visualization of a categorical variable in your dataset.
    - Provide a univariate visualization of a numerical variable in your dataset.
-   **Exploratory data analysis**: 
    - For each of your three research questions, generate at least one data visualization or descriptive statistic. 
    - Discuss and interpret your findings.
-   **Inferential statistical analysis**:
    - For at least one of your research questions, perform a basic statistical analysis (ex. confidence interval, hypothesis test, linear regression). 
    - Discuss and interpret your findings.
-   **Conclusions and future questions**: 
    - Summarize your conclusions and discuss any questions you might interested in exploring in the future. 
    - Are there other types of datasets that would have been helpful to have?

## Part Three: Lightning Talks (15 points), slides due 12/3

3-5 minutes, maximum four slides. You should rehearse your lightning talk in advance and it should include:

-   A quick introduction to your dataset and research questions of interest.
-   An overview of your favorite visualization/descriptive summary/result from your project.

## Part Four: Reflection and Self-evaluation (5 points), due 12/12

You will complete a 1-2 page reflection and self-evaluation on your work this semester for MATH167R. Briefly answer the following questions:

1. Describe at least one aspect of your work for this class of which you are proud. Are there any ways in which you grew this semester?
2. Describe at least one aspect of your work which you could have improved.  
3. Are there other topics related to programming in R and data science that you wish we had covered?

### Grading Rubric

-   Project Proposal: Graded based on completion of all instructions.
-   Final Report:
    -   Exposition (10 points): graded on the clarity of your writing and the appropriateness of your dataset and research questions
    -   Exploratory data analysis (25 points): graded on the correctness of your computations/visualizations, appropriate use of R functions, and the depth/clarity of your explanations
    -   Inferential statistical analysis (25 points): graded on the appropriateness of your analysis, accuracy of your computations and interpretations, appropriate use of R functions, and the depth/clarity of your explanations
    -   Code style/formatting (10 points): to receive full credit, all code, text, and output in your final report should be correctly formatted. Code should be appropriately commented and styled (ex. appropriate variable names).
-   Lightning Talks: graded based on the quality and completeness of your presentation.
-   Reflection and Self-evaluation: Graded based on completion.
