project:
  type: website
  output-dir: docs

website:
  title: "MATH250"
  page-navigation: true
  description: "Homepage for MATH250, Spring 2024 at SJSU"
  open-graph: true
  page-footer:
    right: "Built with [Quarto](https://quarto.org/) based on the website for [STA 210](https://sta210-s22.github.io/website/)."
    left: "&copy; Copyright 2023, Peter A. Gao"

  sidebar:    
    background: "#0055A2"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: syllabus.qmd
            text: Syllabus
          - href: index.qmd
            text: Schedule
      - section: "Weekly materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"

format:
  html:
    theme: [theme.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto


