---
title: "MATH250: Mathematical Methods for Data Visualization"
subtitle: "Spring 2024"
tbl-colwidths: [5,10,20,10,10,10]
draft: false
---

::: column-screen-inset-right
| Week | Date   | Topic                                         | Readings                                 |                         Slides                         |                   HW                   |
|:---------:|-----------|-----------|:----------|:---------:|:---------:|
|  1   | W 1/24 | Overview: Data as representation              |                                          | [Slides 01](slides/01_intro.pdf){.label .label-purple} | [HW 01](hw/hw1.pdf){.label .label-red} |
|  2   | M 1/29 | Highlights of linear algebra                  | Strang I.1 and I.2, Murphy Ch. 7         | [Notes 02](slides/02_notes.pdf){.label .label-purple}                                                       |                                        |
|      | W 1/31 | Highlights of linear algebra                  | Strang I.3 and I.4                       |  [Notes 03](slides/03_notes.pdf){.label .label-purple}                                                      |   [HW 02](hw/hw2.pdf){.label .label-red}      [Lab](hw/matrix-algebra-lab.html){.label .label-red}                                |
|  3   | M 2/5  | Highlights of linear algebra                  | Strang I.5 and I.6                       |  [Notes 04](slides/04_notes.pdf){.label .label-purple}                                                       |                                        |
|      | W 2/7  | Highlights of linear algebra                  | Strang I.7                               |  [Notes 05](slides/05_notes.pdf){.label .label-purple}                                                      |                                        |
|  4   | M 2/12 | Singular value decomposition                  | Strang I.8 and I.9                       |                                                        |                                        |
|      | W 2/14 | Singular value decomposition                  |                                          |                                                     |  [HW 03](hw/hw3.pdf){.label .label-red}      [Lab](hw/SVD-lab.html){.label .label-red}                                          |
|  5   | M 2/19 | Principal components analysis                 | Strang I.10, I.11, and I.12, Murphy 20.1 |                                                        |                                        |
|      | W 2/21 | Principal components analysis                 |                                          |                                                        |                                        |
|  6   | M 2/26 | Linear systems and least squares              | Strang II.1 and II.2                     |                                                        |                                        |
|      | W 2/28 | Linear systems and least squares              |                                          |                                                        |                                        |
|  7   | M 3/4  | Dimension reduction and statistical inference |                                          |                                                        |                                        |
|      | W 3/6  | EXAM I                                        |                                          |                                                        |                                        |
|  8   | M 3/11 | Dimension reduction and statistical inference | Murphy 3.1, 3.2, 20.2                    |                                                        |                                        |
|      | W 3/13 | Dimension reduction and statistical inference |                                          |                                                        |                                        |
|  9   | M 3/18 | Prediction                                    | Murphy Advanced Topics Ch. 18.           |                                                        |                                        |
|      | W 3/20 | Prediction                                    |                                          |                                                        |                                        |
|  10  | M 3/25 | Visualization                                 | Murphy 20.4                              |                                                        |                                        |
|      | W 3/27 | Visualization                                 |                                          |                                                        |                                        |
|      | M 4/1  | *Cesar Chavez Day - No class*                 |                                          |                                                        |                                        |
|      | W 4/3  | *Spring Break - No class*                     |                                          |                                                        |                                        |
|  11  | M 4/8  | Manifold learning                             | Murphy 20.3 and 20.4                     |                                                        |                                        |
|      | W 4/10 | Manifold learning                             |                                          |                                                        |                                        |
|  12  | M 4/15 | Classification                                | Murphy Ch. 9                             |                                                        |                                        |
|      | W 4/17 | Classification                                |                                          |                                                        |                                        |
|  13  | M 4/22 | Clustering                                    | Murphy 21.5                              |                                                        |                                        |
|      | W 4/24 | Clustering                                    |                                          |                                                        |                                        |
|  14  | M 4/29 | Embeddings and LLMs                           | Murphy 20.5                              |                                                        |                                        |
|      | W 5/1  | Review                                        |                                          |                                                        |                                        |
|  15  | M 5/6  | EXAM II                                       |                                          |                                                        |                                        |
|      | W 5/8  | Final presentations                           |                                          |                                                        |                                        |
|  16  | M 5/13 | Final presentations                           |                                          |                                                        |                                        |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides |                    AE                    | Labs | HW  | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋 [Lab 01](hello){.label .label-purple} |  ✍️  |     |      |         |
