---
title: "Linear Systems and Least Squares"
author: "YOUR NAME HERE"
date: "2024-3-13"
format: 
  html:
    embed-resources: true
    code-tools: true
    code-summary: "Code"
---

Review the following tutorial on basic matrix algebra in R and complete the exercises at the bottom. Your solutions should include both R code and any output requested. You may organize your solutions using an R Markdown document or in a pdf/docx format.

You may collaborate with your classmates and consult external resources, but you should write and submit your own answer. **Any classmates with whom you collaborate should be credited at the top of your submission. Similarly, if you consult any external references, you should cite them clearly and explicitly.**



1. Create a vector `x` containing the integers 1 through 100 and compute the length of `x` by taking the square root of the dot product of `x` with itself.

2. Construct the following matrices in R and use matrix functions/operations to answer the following questions.

$$
A=\begin{bmatrix}
		1 & 2 & 3 & 4 \\
		0 & 1 & 1 & 2 \\
		1 & 3 & 4 & 6 
\end{bmatrix}\hspace{2cm}
B=\begin{bmatrix}
		1 & 1 & 2 \\
		2 & 2 & 4 \\
		5 & 6 & 7 \\
		5 & 6 & 8 
\end{bmatrix}
$$

  a. What is $AB$?
  b. What is $B^T A^T$?
  c. Is $AB$ invertible? If so, what is its inverse?
  d. Is $A^T A$ invertible? If so, what is its inverse?
  e. Is $B^T B$ invertible? If so, what is its inverse?
  f. What are the non-zero eigenvalues of $A^T A$? How do they compare to the non-zero eigenvalues of $AA^T$?
  
3. Use matrix operations in R to solve the following system of linear equations:

\begin{align}
7x+2y+z&=30\\
8x+2y-z&=24\\
x+y+z&=12
\end{align}

4. Use a 3d scatter plot to visualize the relationships between the variables `mpg`, `hp`, and `wt` from the `mtcars` dataset (included in R).


  

